# Nueral Network-
* A neural network is a type of machine learning algorithm that is inspired by the structure and function of the human brain. Neural networks are made up of interconnected nodes, called neurons, which process information and send signals to each other.

* To pass messages to the brain the neurons pass the message. messages are passed with nuerons. through the nuerions info passes back and forth through forward or bacward propogation until the the objective is achieved

* it can be used for any kind of data and for complex calculation and processing, with the help of deep learning this is possible.

# AI
* is to mimick human brain into a computer


#images

* pixcels will process one by one each in the nueral network, to the final result, the job of the hidden layers is to pass the info to the next section.

#example
* nose- to nueron - to brain - cover nose

Artificial nueral network vs nueral network


Churn- the rate of customers stop doing bussiness with a company



situation: a bank is facing customer churn , they want to analyze this and find the reason why customers are leaving.

Steps

* understand the data/ import your data

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
path="/content/Churn_Modelling (1).csv"

df= pd.read_csv(path)
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:

df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
#EDA
#findings on basis of exit column
#if credit score is low, person might leave the bank , high creditscore person will stay with the bank
#female customers are more loyal than male customers
#age- young age customers are more prone to switch banks
df.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:


cool= df.groupby(["Exited"])["Gender"].value_counts()
cool[::]
# g = sns.catplot(
#     data=df, kind="bar",
#     x="Exited", y="Gender", hue="sex",
#     errorbar="sd", palette="dark", alpha=.6, height=6
# )
# g.despine(left=True)
# g.set_axis_labels("", "Body mass (g)")
# g.legend.set_title("")

Exited  Gender
0       Male      4559
        Female    3404
1       Female    1139
        Male       898
Name: Gender, dtype: int64

In [ ]:
#look for import columns and depenbdent columns, you must look for coulmns that are responsible for customer churn
X= df.iloc[:, 3:-1]
X

y= df.iloc[:, -1:]

y

      Exited
0          1
1          0
2          1
3          0
4          0
...      ...
9995       0
9996       0
9997       1
9998       1
9999       0

[10000 rows x 1 columns]